#!/usr/bin/with-contenv sh

#Copies config files and creates advanced config file if not present
if [ -f /config/cfg/advanced.yaml ]; then
  echo "Advanced config file detected. Keeping existing files"
else
# copy files incl advanced.yaml
  cp -Rp /opt/config/* /config/
fi

# Always load latest cron settings
ruby /usr/local/sbin/create-cron
# Always writes latest template variables on container startup to config.yaml
# not needed anymore - moved to web gui
# ruby /usr/local/sbin/config-setup

#read nowshowing_schedule.cron on container startup and add to crontab.
chown xyz:xyz /opt/nowshowing_schedule.cron
crontab -u xyz /opt/nowshowing_schedule.cron
crond

echo "Please go to http://hostServerIP:hostPort/admin to configure settings"
